<a href="https://colab.research.google.com/github/julio-monzem/quantum-fintech-credito/blob/main/modelo_preditivo_credito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Cenário

A QuantumFinance está acompanhando um crescimento de inadimplência entre seus clientes e solicita a consultoria
para desenvolver uma análise com base na sua carteira atual de clientes.

Para que a QuantumFinance tome decisões mais precisas sobre concessões de crédito, ela precisa aprimorar seu
modelo de crédito.

Com o objeto de trazer novos clientes com o perfil de baixo risco de crédito desenvolva um modelo de Credit Scoring.

***

>Desafio: Desenvolver o modelo preditivo mediante uso do valor target disponível na base de dados “Base_ScoreCredito_QuantumFinance.csv” e criar um simulador do modelo para os analistas de créditos e gerentes de conta.

### Dicionário: Base de Crédito

***

> ### ID
> ***

|Variável|Descrição|
|--|--|
|id|ID|


> ### Idade
> ***

|Variável|Descrição|
|--|--|
|idade|Idade em anos|

> ### Sexo
> ***

|Variável|Descrição|Categorias|Valores|
|--|--|--|--|
|sexo|Sexo|F|Feminino|
|sexo|Sexo|M|Masculino|

> ### Estado Civil
> ***

|Variável|Descrição|Categorias|
|--|--|--|
|estado_civil|Estado Civil|Solteiro|
|estado_civil|Estado Civil|Casado|
|estado_civil|Estado Civil|Divorciado|


> ### Escola
> ***

|Variável|Descrição|Categorias|Valores|
|--|--|--|--|
|escola|Grau de Instrução|ensino fundam|Até ensino fundamental|
|escola|Grau de Instrução|ensino médio|ensino médio|
|escola|Grau de Instrução|Graduação|Graduação|
|escola|Grau de Instrução|Doutorado|Doutorado|

> ### Trabalha
> ***

|Variável|Descrição|Categorias|Valores|
|--|--|--|--|
|trabalha|Trabalha|1|Sim|
|trabalha|Trabalha|0|Não|

> ### Região da Moradia
> ***

|Variável|Categorias|Valores|
|--|--|--|
|reg_moradia|1|Segmento Geográfico A|
|reg_moradia|2|Segmento Geográfico B|
|reg_moradia|3|Segmento Geográfico C|
|reg_moradia|4|Segmento Geográfico D|
|reg_moradia|5|Segmento Geográfico E|
|reg_moradia|6|Segmento Geográfico F|


> ### Casa Própria
> ***

|Variável|Categorias|Valores|
|--|--|--|
|casa_propria|1|Sim|
|casa_propria|0|Não|

> ### Quantidade de Dependentes
> ***

|Variável|Descrição|
|--|--|
|Qte_dependentes|Quantidade de Dependentes|

> ### Tempo de Trabalho (Meses)
> ***

|Variável|Descrição|
|--|--|
|tempo_ultimoservico|Tempo de trabalho em meses|

> ### Salário
> ***

|Variável|Descrição|
|--|--|
|vl_salario_mil|Salário|

> ### Valor do imóvel (R$)
> ***

|Variável|Descrição|
|--|--|
|vl_imovel_em_mil|Valor do imóvel em Reais|

> ### Quantidade de cartões de crédito
> ***

|Variável|Descrição|
|--|--|
|Qte_cartoes|Quantidade de cartões de crédito|

> ### Quantidade de carros
> ***

|Variável|Descrição|
|--|--|
|Qte_carros|Quantidade de carros|

> ### Credit Scoring
> ***

|Variável|Descrição|
|--|--|
|SCORE_CREDITO|Credit Scoring|

### Análise Descritiva da Base

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/julio-monzem/quantum-fintech-credito/refs/heads/main/Base_ScoreCredito_QuantumFinance.csv'

dados = pd.read_csv(url, delimiter=';')
dados.shape

(10127, 15)

In [ ]:
dados.columns

Index(['id', 'idade', 'sexo', 'estado_civil', 'escola', 'Qte_dependentes',
       'tempo_ultimoservico', 'trabalha', 'vl_salario_mil', 'reg_moradia',
       'casa_propria', 'vl_imovel_em_mil', 'Qte_cartoes', 'Qte_carros',
       'SCORE_CREDITO'],
      dtype='object')

In [ ]:
dados.head()

,id,idade,sexo,estado_civil,escola,Qte_dependentes,tempo_ultimoservico,trabalha,vl_salario_mil,reg_moradia,casa_propria,vl_imovel_em_mil,Qte_cartoes,Qte_carros,SCORE_CREDITO
0,708082083,45,F,casado,graduacao,3,40,1,"40,089665024322",3,0,0,1,1,778
1,708083283,58,M,solteiro,ensino fundam,0,44,1,"66,557645274838",3,0,0,1,0,"276,3"
2,708084558,46,M,divorciado,doutorado,3,35,1,"123,68182089138",6,0,0,1,1,401
3,708085458,34,F,solteiro,mestrado,0,22,1,"19,7159343168329",6,0,0,1,0,"347,4"
4,708086958,49,F,casado,mestrado,2,36,0,0,3,1,437,1,2,476